### ISSUE TITLE
Can you do these 3 functions for php ?

### ISSUE THREAD

**Issue by pyaehein** [YellowOrWhite/go-steam-mobileauth#1]
Hi, can u help me to do some functions in php. I don't know about go language and i am not using it. But i really need these functions in php. Please help me. Thank you.
AddAuthenticator,
FinalizeAddAuthenticator and
GenerateSteamGuardCodeForTime

**Comment by YellowOrWhite** [comment]
Sorry but i'm not gonna do this. If you know PHP it is quite easy to port C# SteamAuth or my lib.
