### ISSUE TITLE
Confirmations and DeviceID

### ISSUE THREAD

**Issue by aport** [YellowOrWhite/go-steam-mobileauth#5]
Other implementations of SteamKit use the account's SteamID instead of random bytes to construct the DeviceID. I believe this matches what the android Steam app does as well.

When using node-steamcommunity, I am able to retrieve my device confirmations.

Using this package, I get the error:

"You can't receive confirmations on this device"

I've changed the code slightly so that my device ID is generated using my account's SteamID, and also verified that the DeviceID generated is identical to those generated by the steam-totp package which is used by node-steamcommunity. Despite this, I still get the above error.

Are there other differences which may lead steam to believe that the request is coming from a different device?

Update: One of my issues was that my identitySecret string was escaped and so it wouldn't decode from base64. Derp. After I changed the code to generate my DeviceID from my SteamID, everything is working.

**Comment by YellowOrWhite** [comment]
Normal use case is to generate DeviceId once, link authenticator, save data (including DeviceId), and than to receive confirmations by always using this data. Why generate DeviceId multiple times? 

I don't think android steam app uses SteamId to generate DeviceId.

**Comment by aport** [comment]
Consider the use case where an account is first linked to steam guard via a phone's mobile app, and later the user wants to use this account with a bot.

According to https://github.com/DoctorMcKay/node-steam-totp the android app does generate a device ID based off your steam ID. Whatever the case, when I use this technique I can perform SteamGuard actions on my account from both my desktop computer (using a bot) and my phone (to which my account steam guard is linked)

**Comment by YellowOrWhite** [comment]
In that case a user has to copy DeviceId from his phone. For android it is in steam.uuid.xml

From your link: "Returns a standardized device ID in the same format as Android device IDs from Valve's official mobile app." Format is the same but actual DeviceId is not. If you need to use the same DeviceId, just use the same one, no need to generate it every time based on some specific input.
